### ISSUE TITLE
Linear search: new languages

### ISSUE THREAD

**Issue by JefvdA** [codinasion/codinasion-dsa#63]
### What programme on codinasion.vercel.app/dsa is affected?

[Linear search](https://github.com/codinasion/codinasion-dsa/tree/master/programme/linear-search)

### What part(s) of the programme would you like to see updated?

Hi there!

The linear search programme does not have these languages:
- Julia
- PHP
- Rust

I'd love to help with those!

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-dsa/blob/master/CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Thanks for noticing this 🤗 

These issues has been created.

More issues will be added soon. If you have any new programme idea, please suggest in #62
