### ISSUE TITLE
Write a PHP programme for Linear Search.

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion-dsa#64]
### Description

Write a programme for Linear Search.

```
Input  : 10 20 80 30 60 50
Target : 30

Output : 3
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-dsa/blob/master/CODE_OF_CONDUCT.md)

**Comment by 9gl** [comment]
Hey @harshraj8843  , I'm interested in contributing to this issue, so before I start working on it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by harshraj8843** [comment]
Hey @9gl 

Thanks for showing your interest 😃 

---

Programme description : Given a list of integers, we have to find the index of the target value

### 🔗 Resources

- https://codinasion.vercel.app/dsa/linear-search
- https://www.geeksforgeeks.org/linear-search
- https://www.tutorialspoint.com/data_structures_algorithms/linear_search_algorithm.htm
