### ISSUE TITLE
Write a Julia programme for Linear Search.

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion-dsa#65]
### Description

Write a programme for Linear Search.

```
Input  : 10 20 80 30 60 50
Target : 30

Output : 4
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-dsa/blob/master/CODE_OF_CONDUCT.md)

**Comment by JefvdA** [comment]
Hey,

Just for clarification for future Julia issues, arrays in Julia start at index 1, so the expected output should be `4` in this case.
